name: Jugad

on:
  push:
    branches: [main]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Zip Folder
        run: zip -jpr dist.zip dist/        


  DeployTest:
    name: Deploy to Test
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: Development
      url: https://github.com/VikashSingh23/heroangular/deployments
    steps:
      - name: Deploy to S3
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Sync to S3
        run: |
         aws s3 sync . s3://front-prod-s3-bucket/  --exclude "node_modules/*" --exclude "src/*" --exclude "e2e/*" --exclude ".github/*"
  DeployProd:
    name: Deploy to Production
    needs: [DeployTest, Build]
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://github.com/VikashSingh23/heroangular/deployments
    steps:
      - name: Deploy to S3
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Sync to S3
        run: |
         aws s3 sync . s3://front-prod-s3-bucket/  --exclude "node_modules/*" --exclude "src/*" --exclude "e2e/*" --exclude ".github/*"