name: CI + CD

on:
  push:
    branches:
    - main

jobs:
  Build:
    name: Build and Package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::426707758245:role/OpenIDConnection
          role-session-name: GitHub-Action-Role
          aws-region: ap-south-1
          
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
         node-version: 16

      - name: Install dependencies
        run: npm install

  DeployTest:
    name: Deploy to Test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: Development
      url: https://front-test-s3-bucket.s3-ap-south-1.amazonaws.com
    steps:
      - name: Deploy
        run: |
          aws s3 sync . s3://front-test-s3-bucket/ --exclude "node_modules/*" --exclude "src/*" --exclude "e2e/*" --exclude ".github/*"

  DeployProd:
    name: Deploy to Production
    if: github.event_name == 'push' && github.ref != 'refs/heads/main'
    needs: [DeployTest]
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://front-prod-s3-bucket.s3-ap-south-1.amazonaws.com
    steps:
      - name: Deploy
        run: |
          aws s3 sync . s3://front-prod-s3-bucket/ --exclude "node_modules/*" --exclude "src/*" --exclude "e2e/*" --exclude ".github/*"
