name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install


      - name: 'Create env file'
        run: |
          touch .env
          API_ENDPOINT="https://xxx.execute-api.us-west-2.amazonaws.com" >> .env
          API_KEY=${{ secrets.API_KEY }} >> .env
          cat .env
