name: CI + CD

on:
  push:
    branches:
      -main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:       
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1      

      - name: Checkout
        uses: actions/checkout@v2
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        
      - name: Deploy
        run: |
            $REPOSITORY_VAR   
        
    env:
        REPOSITORY_VAR: ${{ vars.REPOSITORY_VAR }}  
        

  DeployTest:
    name: Deploy to Test 
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Development
      url: https://github.com/VikashSingh23/heroangular/settings/environments/1071081436/edit
        
  DeployProd:
    name: Deploy to Production 
    needs: [DeployTest]
    runs-on: ubuntu-latest
    environment: 
      name: Production
      #url: https://github.com/VikashSingh23/heroangular/settings/environments/1068439192/edit
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Deploy
        run: 
          aws s3 sync . s3://front-prod-s3-bucket/  --exclude "node_modules/*" --exclude "src/*" --exclude "e2e/*" --exclude ".github/*"
