name: Jugad2

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Zip Folder
        run: zip -jpr dist.zip dist/

  deployDev:
    name: Deploy to Dev
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: Development
      url: ${{ secrets.TEST_BUCKET_URL }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: dist-zip

      - name: Unzip artifact
        run: unzip dist.zip

      - name: Configure AWS credentials
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "[default]" > ~/.aws/config
          echo "region=ap-south-1" >> ~/.aws/config

      - name: Install AWS CLI
        run: |
          sudo apt-get install -y python3-pip
          pip3 install --user awscli

      - name: Deploy to S3
        run: |
          aws s3 sync ./dist/ s3://${{ secrets.TEST_BUCKET_NAME }}/ --exclude "node_modules/*" --exclude "src/*" --exclude "e2e/*" --exclude ".github/*"

      - name: Set Environment File
        run: echo "TEST_APP_URL=https://$({{ secrets.TEST_BUCKET_NAME }}).s3.amazonaws.com" >> $GITHUB_ENV

  deployProd:
    name: Deploy to Production
    needs: deployDev
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: ${{ secrets.PROD_BUCKET_URL }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: dist-zip

      - name: Unzip artifact
        run: unzip dist.zip

      - name: Configure AWS credentials
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "[default]" > ~/.aws/config
          echo "region=ap-south-1" >> ~/.aws/config

      - name: Install AWS CLI
        run: |
          sudo apt-get install -y python3-pip
          pip3 install --user awscli

      - name: Deploy to S3
        run: |
          aws s3 sync ./dist/ s3://${{ secrets.PROD_BUCKET_NAME }}/ --exclude "node_modules/*" --exclude "src/*" --exclude "e2e/*" --exclude ".github/*"

