name: Build and Deploy

on:
  push:
    branches:
    - main

env:
  BUCKET_NAME : "front-test-s3-bucket"
  AWS_REGION : "ap-south-1"
  GITHUB_REF: "main"


jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::426707758245:role/OpenIDConnection
          role-session-name: GitHub-Action-Role
          aws-region: ${{ env.AWS_REGION }}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

    #- name: Run tests
      #run: npm run test:headless

      - name: Build
        run: npm run build

      - name:  Copy build to S3
        run: |            
          aws s3 sync ./dist s3://front-test-s3-bucket/ 
          zip -r dist.zip dist  
          aws s3 sync ./dist.zip s3://front-test-s3-bucket/ 


 
