name: Build and Deploy

on:
  push:
    branches:
    - main

env:
  BUCKET_NAME : "front-test-s3-bucket"
  AWS_REGION : "ap-south-1"
  GITHUB_REF: "main"


jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::426707758245:role/OpenIDConnection
          role-session-name: GitHub-Action-Role
          aws-region: ${{ env.AWS_REGION }}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

    #- name: Run tests
      #run: npm run test:headless

      - name: Build
        run: npm run build
    
     # - name: Deploy
      #  if: success()
       # run: aws s3 sync . s3://front-test-s3-bucket
       
 # Copy build directory to S3
     # - name:  Copy build to S3
     #   run: |
     #     zip -r dist.zip dist            
          #aws s3 sync  ${GITHUB_WORKSPACE}/artifacts/dist.zip s3://${{ env.BUCKET_NAME }}
      #    aws s3 sync ./dist s3://front-test-s3-bucket/
     #     cp dist/* .
          #aws s3 sync . s3://front-test-s3-bucket
      - name: Upload Report
        uses: actions/upload-artifact@v2
        with:
          name: HTML_Report
          path: cypress/reports/Result
      - name: Upload S3    
        uses: shallwefootball/s3-upload-action@master
        id: S3
        with:

          aws_bucket: front-test-s3-bucket
          source_dir: cypress/reports/Result
          branch: main
          folder: dist
