name: Workflow for URL Shortner App
on:
  workflow_call:
    secrets:
      token: # SURGE_TOKEN
        description: the token for deployment service
        required: true
    inputs:
      domain:
        description: the domain to use
        required: true
        type: string
jobs:                            
  Build:                            
    runs-on: ubuntu-latest        
    strategy:
      matrix:
        node-version: [16.x]
    environment:
      name: Development           
    steps:
      - uses: actions/checkout@v2 
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install          
      - run: npm run build 
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy to S3
        run: |
          aws s3 sync . s3://testfrontbucketmy/  --exclude "node_modules/*" --exclude "src/*" --exclude "e2e/*" --exclude ".github/*"         
    env:                          
      #DB_Username: ${{ secrets.TEST_DB_USERNAME }}
      #DB_Password: ${{ secrets.TEST_DB_PASSWORD }}
      #DB_ClusterUri: ${{ secrets.TEST_DB_CLUSTERURI }}
      #DB_Name: ${{ secrets.TEST_DB_NAME }}
      BASE_URL: ${{ secrets.TEST_BASE_URL }}
  deploy:                        
    needs: Build                  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    environment:
      name: Production
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npn build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy to S3
        run: |
          aws s3 sync . s3://testfrontbucketmy/   --exclude "node_modules/*" --exclude "src/*" --exclude "e2e/*" --exclude ".github/*" 
    env:
      #DB_Username: ${{ secrets.PROD_DB_USERNAME }}
      #DB_Password: ${{ secrets.PROD_DB_PASSWORD }}
      #DB_ClusterUri: ${{ secrets.PROD_DB_CLUSTERURI }}
      #DB_Name: ${{ secrets.PROD_DB_NAME }}
      BASE_URL: ${{ secrets.PROD_BASE_URL }}
