name: Build and Deploy

on:
  push:
    branches:
    - main

env:
  BUCKET_NAME : "front-test-s3-bucket"
  AWS_REGION : "ap-south-1"
  GITHUB_REF: "main"


jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::426707758245:role/OpenIDConnection
          role-session-name: GitHub-Action-Role
          aws-region: ${{ env.AWS_REGION }}

    #  - name: Extract branch name
     #  run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      #  id: extract_branch
  #    - name: Extract commit hash
   #     shell: bash
    #    run: echo "##[set-output name=commit_hash;]$(echo "$GITHUB_SHA")"
     #   id: extract_hash           
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm run build
     # - run: npm run lint

      - name: Make Artifact directory
        run: mkdir -p ./artifacts/dist

      # Copy build directory to S3
      - name:  Copy build to S3
        run: |
          zip -r ./artifacts/dist/project.zip . -x node_modules/**\* .git/**\* .guthub/**\* src/**\* e2e/**\*                  
          aws s3 sync  ${GITHUB_WORKSPACE}/artifacts/dist s3://${{ env.BUCKET_NAME }}
