name: AWS Zip

on:
  push:
    branches:
     - main
env:
  BUCKET_NAME : testfrontbucketmy
  AWS_REGION : ap-south-1
permissions:
      id-token: write   
      contents: read    
jobs:
  Test:
    name: Build For Test
    runs-on: ubuntu-latest
    
    environment:
      name: Development
      
    steps:
      - uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::648821256272:role/Github-Action-Role
          role-session-name: Github-Action-Role
          aws-region: ap-south-1
          
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
         node-version: 16

      - name: Install dependencies
        run: npm install
        
    #- name: Run tests
      #run: npm run test:headless

      - name: Build
        run: npm run build        
      - name: Zip Folder 
        run: zip -jpr dist.zip dist/
        
      - name: Deploy
        if: success()
        run: |        
         aws s3 sync . s3://${{ env.BUCKET_NAME }}/  --exclude "node_modules/*" --exclude "src/*" --exclude "e2e/*" --exclude ".github/*"
         aws s3 sync ./dist/ s3://${{ env.BUCKET_NAME }}/
 
  Prod:
    needs: Test
    name: Build and Prod
    runs-on: ubuntu-latest
    
    environment:
      name: Production
      
    steps:
      - uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::648821256272:role/Github-Action-Role
          role-session-name: Github-Action-Role
          aws-region: ap-south-1
          
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
         node-version: 16

      - name: Install dependencies
        run: npm install
         
    #- name: Run tests
      #run: npm run test:headless

      - name: Build
        run: npm run build        
      - name: Zip Folder 
        run: zip -jpr dist.zip dist/
        
      - name : create host.ts
        run : |
         #touch .env
         cat > .env
         echo 'export var host = "http:localhost:3000"' >> .env

        
      - name: Deploy
        if: success()
        run: |        
         aws s3 sync . s3://${{ env.BUCKET_NAME }}/  --exclude "node_modules/*" --exclude "src/*" --exclude "e2e/*" --exclude ".github/*"
         aws s3 sync ./dist/ s3://${{ env.BUCKET_NAME }}/
